# Generated by Django 5.1.1 on 2024-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_email_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchildrelation',
            name='child_icon',
            field=models.ImageField(blank=True, null=True, upload_to='child_icons/'),
        ),
        migrations.AddField(
            model_name='parentchildrelation',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
