# Generated by Django 5.1.1 on 2024-11-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parentchildrelation_child_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildrelation',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentchildrelation',
            name='child_name',
            field=models.CharField(default='default_child_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentchildrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
