# Generated by Django 5.1.1 on 2024-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_aichatbot_question_userprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="question",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="current_question",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=255),
        ),
    ]
