# Generated by Django 5.1.3 on 2024-11-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_question_image_useranswerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.CharField(max_length=100)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0, help_text='Give a rating between 0 to 5 stars.')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('week', models.IntegerField()),
                ('lesson_type', models.CharField(choices=[('Exercise', 'Exercise'), ('Speaking Practice', 'Speaking Practice'), ('Quiz', 'Quiz')], max_length=50)),
                ('order', models.IntegerField(help_text='Specify the order of the lesson for each week.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.course')),
            ],
            options={
                'ordering': ['week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Lesson'), ('mcq', 'Multiple Choice Question'), ('match', 'Match')], max_length=50)),
                ('answer', models.JSONField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.lesson')),
            ],
            options={
                'ordering': ['lesson'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.exercise')),
            ],
        ),
    ]
