# Generated by Django 5.1.1 on 2024-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_userprofile_parent_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAnswerHistory',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
