# Generated by Django 5.1.1 on 2024-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userprofile_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
