# Generated by Django 5.1.1 on 2024-11-12 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_customized_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistchildrelation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='therapistchildrelation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='therapistchildrelation',
            name='child_icon',
            field=models.ImageField(blank=True, null=True, upload_to='child_icons/'),
        ),
        migrations.AddField(
            model_name='therapistchildrelation',
            name='child_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistchildrelation',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistchildrelation',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistchildrequest',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistchildrequest',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
